<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('clientes')->insert([
            [
                'razon_social' => 'S/N',
                'nit' => '11062189',
                'telefono' => '762123456',
                'direccion' => 'Av. 6 de Agosto 123, La Paz',
                'email' => 'empresa@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'TECNO SA',
                'nit' => '6312345678',
                'telefono' => '631234567',
                'direccion' => 'Av. Santa Cruz 456, Cochabamba',
                'email' => 'empresa@email.com',
                'estado' => 1,
                 'created_at' => date('Y-m-d H:i:s'),
                 'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'AGRO LTDA',
                'nit' => '7529876543',
                'telefono' => '752987654',
                'direccion' => 'Av. Villazón 789, Potosí',
                'email' => 'empresa@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ], [
                'razon_social' => 'EDUCA SRL',
                'nit' => '6211111111',
                'telefono' => '621111111',
                'direccion' => 'Av. Ballivián 111,Sucre',
                'email' => 'empresa@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'TURISMO SA',
                'nit' => '7512222222',
                'telefono' => '751222222',
                'direccion' => 'Av. Camacho 202,Oruro',
                'email' => 'empresa@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'MODA SRL',
                'nit' => '7623333333',
                'telefono' => '762333333',
                'direccion' => 'Av. Arce 313, 
            La Paz',
            'email' => 'empresa@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'AUTO SA',
                'nit' => '6314444444',
                'telefono' => '631444444',
                'direccion' => 'Av. Blanco Galindo 414, 
            Cochabamba',
            'email' => 'empresa@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'ALBA LTDA',
                'nit' => '7525555555',
                'telefono' => '752555555',
                'direccion' => 'Av. Litoral 515, 
            Potosí',
            'email' => 'empresa@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'SALUD SRL',
                'nit' => '6216666666',
                'telefono' => '621666666',
                'direccion' => 'Av. Juana Azurduy 616, 
            Sucre',
            'email' => 'empresa@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Empresa Uno SRL',
                'nit' => '1121314151',
                'telefono' => '762123456',
                'direccion' => 'Av. Ballivian 123,La Paz',
                'email' => 'empresa@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Comercial Boliviana SA',
                'nit' => '2121222324',
                'telefono' => '631234567',
                'direccion' => 'Calle Sucre 456, Cochabamba',
                'email' => 'empresa@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Bolivia Exportaciones EIRL',
                'nit' => '3131323336',
                'telefono' => '627891111',
                'direccion' => 'Av. Circunvalación 789, Santa Cruz',
                'email' => 'empresa@email.com',
                'estado' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Constructora Andina Ltda.',
                'nit' => '4041424348',
                'telefono' => '752345678',
                'direccion' => 'Calle Murillo 567, Oruro',
                'email' => 'empresa@email.com',
                'estado' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Servicios Integrales SA',
                'nit' => '5051525356',
                'telefono' => '761234567',
                'direccion' => 'Av. Arce 890, La Paz',
                'email' => 'empresa@email.com',
                'estado' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Juan Pérez',
                'nit' => '4623456',
                'telefono' => '762987654',
                'direccion' => 'Calle Bolívar 123, La Paz',
                'email' => 'juan.perez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'María González',
                'nit' => '7854321',
                'telefono' => '631234567',
                'direccion' => 'Av. Sucre 456, Cochabamba',
                'email' => 'maria.gonzalez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Carlos Rodríguez',
                'nit' => '9876543',
                'telefono' => '752345678',
                'direccion' => 'Calle Pando 789, Santa Cruz',
                'email' => 'carlos.rodriguez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Ana López',
                'nit' => '6543210',
                'telefono' => '760123456',
                'direccion' => 'Av. Arce 890, La Paz',
                'email' => 'ana.lopez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Pedro Sánchez',
                'nit' => '1234567',
                'telefono' => '621234567',
                'direccion' => 'Calle Bolívar 567, Oruro',
                'email' => 'pedro.sanchez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Empresa Seis SRL',
                'nit' => '6061626360',
                'telefono' => '76345678',
                'direccion' => 'Av. San Martín 123, La Paz',
                'email' => 'empresa.seis@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Empresa Siete SA',
                'nit' => '7071727374',
                'telefono' => '76234567',
                'direccion' => 'Calle Bolívar 789, Cochabamba',
                'email' => 'empresa.siete@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Empresa Ocho Ltda.',
                'nit' => '8081828386',
                'telefono' => '76123456',
                'direccion' => 'Av. Libertad 456, Santa Cruz',
                'email' => 'empresa.ocho@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Empresa Nueve SA',
                'nit' => '9091929398',
                'telefono' => '76245678',
                'direccion' => 'Av. América 123, La Paz',
                'email' => 'empresa.nueve@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Empresa Diez SRL',
                'nit' => '101102103106',
                'telefono' => '76345678',
                'direccion' => 'Calle Sucre 789, Cochabamba',
                'email' => 'empresa.diez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Luisa Martínez',
                'nit' => '1122334',
                'telefono' => '76456789',
                'direccion' => 'Calle Bolívar 567, La Paz',
                'email' => 'luisa.martinez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Ricardo Vargas',
                'nit' => '5566778',
                'telefono' => '76234567',
                'direccion' => 'Av. Sucre 123, Cochabamba',
                'email' => 'ricardo.vargas@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Marta Pérez',
                'nit' => '9998887',
                'telefono' => '76123456',
                'direccion' => 'Av. América 456, Santa Cruz',
                'email' => 'marta.perez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Javier Fernández',
                'nit' => '4445556',
                'telefono' => '76456789',
                'direccion' => 'Calle Murillo 123, La Paz',
                'email' => 'javier.fernandez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Silvia Rodríguez',
                'nit' => '8887776',
                'telefono' => '76234567',
                'direccion' => 'Av. Arce 789, Cochabamba',
                'email' => 'silvia.rodriguez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Carlos Soto',
                'nit' => '3332221',
                'telefono' => '76123456',
                'direccion' => 'Calle Sucre 456, Santa Cruz',
                'email' => 'carlos.soto@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Fernanda López',
                'nit' => '1110009',
                'telefono' => '76456789',
                'direccion' => 'Av. Ballivian 123, La Paz',
                'email' => 'fernanda.lopez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Jorge Medina',
                'nit' => '7776665',
                'telefono' => '76234567',
                'direccion' => 'Av. Principal 456, Cochabamba',
                'email' => 'jorge.medina@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Laura Sánchez',
                'nit' => '5554443',
                'telefono' => '76123456',
                'direccion' => 'Calle Murillo 789, Santa Cruz',
                'email' => 'laura.sanchez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Andrés González',
                'nit' => '2221110',
                'telefono' => '76456789',
                'direccion' => 'Av. Sucre 123, La Paz',
                'email' => 'andres.gonzalez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Gabriela Flores',
                'nit' => '10111213',
                'telefono' => '76234567',
                'direccion' => 'Calle Sucre 123, Cochabamba',
                'email' => 'gabriela.flores@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Roberto Mendoza',
                'nit' => '14151617',
                'telefono' => '76123456',
                'direccion' => 'Av. América 456, Santa Cruz',
                'email' => 'roberto.mendoza@email.com',
                'created_at' => date('Y-m-d H:i:s'),
                'estado' => 1,
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Carmen Torres',
                'nit' => '18192021',
                'telefono' => '76456789',
                'direccion' => 'Calle Bolívar 123, La Paz',
                'email' => 'carmen.torres@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Alejandro Vargas',
                'nit' => '22232425',
                'telefono' => '76234567',
                'direccion' => 'Av. Arce 789, Cochabamba',
                'email' => 'alejandro.vargas@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Isabel García',
                'nit' => '26272829',
                'telefono' => '76123456',
                'direccion' => 'Calle Murillo 456, La Paz',
                'email' => 'isabel.garcia@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Martín Silva',
                'nit' => '30313233',
                'telefono' => '76456789',
                'direccion' => 'Av. Sucre 123, Cochabamba',
                'email' => 'martin.silva@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Laura Pérez',
                'nit' => '34353637',
                'telefono' => '76234567',
                'direccion' => 'Calle Bolívar 456, Santa Cruz',
                'email' => 'laura.perez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Pedro Soto',
                'nit' => '38394041',
                'telefono' => '76123456',
                'direccion' => 'Av. América 789, La Paz',
                'email' => 'pedro.soto@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Mariana González',
                'nit' => '42434445',
                'telefono' => '76456789',
                'direccion' => 'Av. Ballivian 123, Cochabamba',
                'email' => 'mariana.gonzalez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'razon_social' => 'Carlos López',
                'nit' => '46474849',
                'telefono' => '76234567',
                'direccion' => 'Calle Sucre 456, Santa Cruz',
                'email' => 'carlos.lopez@email.com',
                'estado' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],

        ]);
    }
}
