<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosSeeder extends Seeder
{
    /**
     * En construccion....
     */
    public function run(): void
    {
        DB::table('productos')->insert([
            [
                'categoria_id' => '1',
                'barcode' => '110',
                'descripcion' => 'Corrector liquido 9m',
                'unidad_medida' => 'PIEZA',
                'cantidad_unidad' => 1,
                'costo_actual' => null,
                'porcentaje_margen' => 30.00,
                'precio_venta' => null,
                'imagen' => 'eMjk2Dqz4WEhguppBaC01PB35PCLojFWZQkUkhAa.jpg',
                'stock_minimo' => 18.00,
                'estado' => '1',
                'marca_id' => 11,
                'origen_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'categoria_id' => '1',
                'barcode' => '123',
                'descripcion' => 'Papel Bond Tamaño Carta pqte. de 500 hojas',
                'unidad_medida' => 'PAQUETE',
                'cantidad_unidad' => 1,
                'costo_actual' => null,
                'porcentaje_margen' => 30.00,
                'precio_venta' => null,
                'imagen' => 'pMvLqrxJux2NDql2tOrT7cx4nNLrDvwSHnkvc9Fn.jpg',
                'stock_minimo' => 18.00,
                'estado' => '1',
                'marca_id' => 5,
                'origen_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                
            ],
            [
                'categoria_id' => '1',
                'barcode' => '1234',
                'descripcion' => 'Marcador de agua p/pizarra color azul',
                'unidad_medida' => 'PIEZA',
                'cantidad_unidad' => '1',
                'costo_actual' => null,
                'porcentaje_margen' => 30.00,
                'precio_venta' => null,
                'imagen' => 'QRuqTQz3J9tyAxrjLXPH8Q3O6gR3NdsidPGHlNlz.png',
                'stock_minimo' => 18.00,
                'estado' => '1',
                'marca_id' => 11,
                'origen_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                
            ],
            [
                'categoria_id' => '1',
                'barcode' => '100',
                'descripcion' => 'Corrector en cinta 8M x 5mm',
                'unidad_medida' => 'PIEZA',
                'cantidad_unidad' => '1',
                'costo_actual' => null,
                'porcentaje_margen' => 30.00,
                'precio_venta' => null,
                'imagen' => 'MTK507leAMhacvQcfhA6LVup9NXGXVuN4XGXjb5D.jpg',
                'stock_minimo' => 18.00,
                'estado' => '1',
                'marca_id' => 11,
                'origen_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                
            ],
            [
                'categoria_id' => '1',
                'barcode' => '7772115250306',
                'descripcion' => 'Corrector liquido magico con base solvente',
                'unidad_medida' => 'PIEZA',
                'cantidad_unidad' => '1',
                'costo_actual' => null,
                'porcentaje_margen' => 30.00,
                'precio_venta' => null,
                'imagen' => 'xs6WxxDHjE2qpW34qf7FQVTzl2mqZJOBdXuCAmjL.jpg',
                'stock_minimo' => 18.00,
                'estado' => '1',
                'marca_id' => 11,
                'origen_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                
            ],
            [
                'categoria_id' => '1',
                'barcode' => '8003511414061',
                'descripcion' => 'Caja de lapices de color Jumbo de 12 und.',
                'unidad_medida' => 'PIEZA',
                'cantidad_unidad' => '1',
                'costo_actual' => null,
                'porcentaje_margen' => 30.00,
                'precio_venta' => null,
                'imagen' => 'pE2Dw1i7vanFzSA2j2bejLWL7hQzodzMj8NQTWSF.jpg',
                'stock_minimo' => 18.00,
                'estado' => '1',
                'marca_id' => 11,
                'origen_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                
            ],
            [
                'categoria_id' => '1',
                'barcode' => '4902505084584',
                'descripcion' => 'Boligrafo color azul BP-S 0.5 mm',
                'unidad_medida' => 'PIEZA',
                'cantidad_unidad' => '1',
                'costo_actual' => null,
                'porcentaje_margen' => 30.00,
                'precio_venta' => null,
                'imagen' => 'AQJFAxUvyTKfPmN2ZnWbUcxrSSr9kCtxtDb2QTov.png',
                'stock_minimo' => 18.00,
                'estado' => '1',
                'marca_id' => 11,
                'origen_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                
            ],
            [
                'categoria_id' => '1',
                'barcode' => '6973963020443',
                'descripcion' => 'PORTAMINAS 0.5mm CUERPO METALICO',
                'unidad_medida' => 'PIEZA',
                'cantidad_unidad' => '1',
                'costo_actual' => null,
                'porcentaje_margen' => 30.00,
                'precio_venta' => null,
                'imagen' => '6BTnwsQeCuOceABDZLlMGi87Itg0CVlpCEsD24Q7.jpg',
                'stock_minimo' => 18.00,
                'estado' => '1',
                'marca_id' => 11,
                'origen_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                
            ],
            [
                'categoria_id' => '1',
                'barcode' => '7754111562010',
                'descripcion' => 'Bolígrafo Faber Castell 062 0.5mm Color azul',
                'unidad_medida' => 'PIEZA',
                'cantidad_unidad' => '1',
                'costo_actual' => null,
                'porcentaje_margen' => 30.00,
                'precio_venta' => null,
                'imagen' => 'KCOENyopMlzT66Eor4AJIUHYU6kq3jDzE4wyoqlg.jpg',
                'stock_minimo' => 18.00,
                'estado' => '1',
                'marca_id' => 11,
                'origen_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                
            ],
            [
                'categoria_id' => '1',
                'barcode' => '40267203',
                'descripcion' => 'PEGAMENTO EN BARRA 21 GR. ',
                'unidad_medida' => 'PIEZA',
                'cantidad_unidad' => '1',
                'costo_actual' => null,
                'porcentaje_margen' => 30.00,
                'precio_venta' => null,
                'imagen' => 'd486b1lwPpDIyITDcM7xItpXrLpV7F1uZFlfeacz.jpg',
                'stock_minimo' => 18.00,
                'estado' => '1',
                'marca_id' => 11,
                'origen_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                
            ],
            [
                'categoria_id' => '1',
                'barcode' => '12345',
                'descripcion' => 'Goma Miga de pan milan 430',
                'unidad_medida' => 'PIEZA',
                'cantidad_unidad' => '1',
                'costo_actual' => null,
                'porcentaje_margen' => 30.00,
                'precio_venta' => null,
                'imagen' => 'V9HDttcdfqhW0OEjZOzxFQ6oG8lX3VH5HneJU8Jx.jpg',
                'stock_minimo' => 18.00,
                'estado' => '1',
                'marca_id' => 11,
                'origen_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                
            ],
            [
                'categoria_id' => '1',
                'barcode' => '111',
                'descripcion' => 'PLASTILINA 12 COLORES',
                'unidad_medida' => 'PIEZA',
                'cantidad_unidad' => '1',
                'costo_actual' => null,
                'porcentaje_margen' => 30.00,
                'precio_venta' => null,
                'imagen' => 'mnCxULmZ7sFhojptGR9etBg4yQBRdA3Nnv99cb66.jpg',
                'stock_minimo' => 18.00,
                'estado' => '1',
                'marca_id' => 11,
                'origen_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                
            ],
        ]);
    }
}
